GET http://localhost:8000/api/search?q=one piece HTTP/1.1

###

POST http://localhost:8000/api/token/ HTTP/1.1
Content-Type: application/json

{
    "username": "admin",
    "password": "admin123"
}

###

POST http://localhost:8000/api/favorites/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ5ODM4NTIyLCJpYXQiOjE3NDk4MzgyMjIsImp0aSI6IjNkZWJlOTE1NWI1NzQ4ZjRhMjAyYmI2YTQ1YjJhMjRlIiwidXNlcl9pZCI6MX0.4MOuTKPGr19UkskVfLSRJFb8ruOy8tuXpMqDtdTs3OI

{
    "id": "32d76d19-8a05-4db0-9fc2-e0b0648fe9d0",
    "title": "Solo Leveling",
    "cover_url": "https://uploads.mangadex.org/covers/e6583e52-1125-4c50-8db4-e8d6cf3fb144/cover.jpg"
}

###
GET http://localhost:8000/api/user-favorites/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ5ODg2MjA2LCJpYXQiOjE3NDk4ODU2MDYsImp0aSI6IjQwMTgwMjEyZWVhMTRlYTM5OTNmYTliODM4MjFkMGZjIiwidXNlcl9pZCI6MX0.Et3gllXG5tiM9g5Yjw67Dmnhhs449Xm352OM0PnGx9w
###

DELETE http://localhost:8000/api/favorites/2/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ5ODg2MjA2LCJpYXQiOjE3NDk4ODU2MDYsImp0aSI6IjQwMTgwMjEyZWVhMTRlYTM5OTNmYTliODM4MjFkMGZjIiwidXNlcl9pZCI6MX0.Et3gllXG5tiM9g5Yjw67Dmnhhs449Xm352OM0PnGx9w

