GET http://localhost:8000/api/search?q=one piece HTTP/1.1

###

POST http://localhost:8000/api/token/ HTTP/1.1
Content-Type: application/json

{
    "username": "admin",
    "password": "admin123"
}

###

POST http://localhost:8000/api/favorites/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ5OTgyOTkxLCJpYXQiOjE3NDk5ODIzOTEsImp0aSI6IjI3ZTZlM2JlODAyNTQ4YjhhZWQ2OTNmNWFhYTNlODgzIiwidXNlcl9pZCI6MX0.3HNWmkgzRjDECiXsWMkXk_tZEEKx3Jb-c8GoSAzba4M

{
    "id": "32d76d19-8a05-4db0-9fc2-e0b0648fe9d0",
    "title": "Solo Leveling",
    "cover_url": "https://uploads.mangadex.org/covers/e6583e52-1125-4c50-8db4-e8d6cf3fb144/cover.jpg"
}

###
GET http://localhost:8000/api/user-favorites/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUwNTQ3NDc2LCJpYXQiOjE3NTA1NDcxNzYsImp0aSI6IjQ2Y2I4NDQwZjgxMjQ3YTQ4ZjEwNTBiZDk4YTUwZjM1IiwidXNlcl9pZCI6MX0.ozj4i_v19Hor8Li9sP_jybxb_vL5zjk_9EUY_3a_wJg

DELETE http://localhost:8000/api/favorites/4/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ5OTgyOTkxLCJpYXQiOjE3NDk5ODIzOTEsImp0aSI6IjI3ZTZlM2JlODAyNTQ4YjhhZWQ2OTNmNWFhYTNlODgzIiwidXNlcl9pZCI6MX0.3HNWmkgzRjDECiXsWMkXk_tZEEKx3Jb-c8GoSAzba4M

####

POST http://localhost:8000/api/login/ HTTP/1.1
Content-Type: application/json

{
    "username": "admin1",
    "password": "admin123"
}

###
POST http://localhost:8000/api/user/change-password/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUwNjMwODQzLCJpYXQiOjE3NTA2MzA1NDMsImp0aSI6ImU4MDU4N2QwNzY0ZTRkODNiMDFlNTcyN2E5NjcyYTRlIiwidXNlcl9pZCI6OH0.z9NKV4Bx38a6JAwzof25thpkQY_DokTtk6DF82tAT-o

{
    "old_password": "adminasd",
    "new_password": "123213",
    "confirm_new_password": "ad2425ascminasd"
}

###

GET http://localhost:8000/api/user/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUwNjMxODE1LCJpYXQiOjE3NTA2MzE1MTUsImp0aSI6IjQ1YWRiZDUzMDIxYzRlYjM5MjdmZjA3NzljMTEyZjc3IiwidXNlcl9pZCI6OH0.ZgKEE3be_U-AUPPB_FnfqDG8bP-lxYeYoBQkLOHlGws

###

PATCH http://localhost:8000/api/user/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUwNjA3NjczLCJpYXQiOjE3NTA2MDczNzMsImp0aSI6ImEzMGY0NDdiNjJmNTQ2MzhiMTk0MzU5NDA0ZmRmMTUyIiwidXNlcl9pZCI6Nn0.mh5HNcaorc9ryfPuKE9oiimYftTSMRnf1xDaWaEQk4Q

{
    "first_name": "user"
}

###

POST http://localhost:8000/api/user-favorites/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUwNTQzOTQyLCJpYXQiOjE3NTA1NDM2NDIsImp0aSI6ImVlOWZhNDJiZjg0OTQxMzk4NzAyZGQxYmVjNjkzYTlhIiwidXNlcl9pZCI6MX0.ldAMocEUORx7kQvgRrz2UX45BBqndDXBV4BY2qXowH4

{
    "id": "1",
    "title": "Hajime no Ippo",
    "status": "Ongoing",
    "cover_art": "image"
}

###

GET http://localhost:8000/api/user-favorites/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUwNTQ3MjQyLCJpYXQiOjE3NTA1NDY5NDIsImp0aSI6ImM4ZjVlMTU3ZWE2ZTRjMDliZTNiZDBiZDhkMTNhZDViIiwidXNlcl9pZCI6MX0.a2ojcY4d4NtX5tPvuLoD0RyUA3a08_XIKDIjRhzZRPY
###

DELETE http://localhost:8000/api/user-favorites/1/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUwNTQzOTQyLCJpYXQiOjE3NTA1NDM2NDIsImp0aSI6ImVlOWZhNDJiZjg0OTQxMzk4NzAyZGQxYmVjNjkzYTlhIiwidXNlcl9pZCI6MX0.ldAMocEUORx7kQvgRrz2UX45BBqndDXBV4BY2qXowH4